#!/usr/bin/env bash
#init file

MY_PID="$$"
echo $MY_PID
start () {
	./manage_my_process&
        echo $! > /var/run/my_process.pid
	echo "manage_my_process started"
}

stop () {
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
}

restart () {
	rm /var/run/my_process.pid
	echo $! > /var/run/my_process.pid
#	cat /var/run/my_process.pid > MY_PID
	echo $MY_PID
	kill $MY_PID
        echo "manage_my_process restarted"
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                restart
                ;;
        *)
                echo "Usage: manage_my_process {start|stop|restart}"
                exit 1
                ;;
esac
exit $?
