#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and "hi" the 9th time

n=1
while [ $n -le 20 ]; do
	echo $n
	if [ $n = 4 ];
	then
		echo bad luck from China
	fi
	if [ $n = 9 ];
	then
		echo bad luck from Japan
	fi
	if [ $n = 17 ];
	then
		echo bad luck from Italy
	fi
	n=$(( n+1 ))
done
