#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and "hi" the 9th time

hour=0
minute=1
while [ $hour -le 12 ]; do
	echo $hour
	while [ $minute -le 59 ]; do
		echo $minute
		minute=$(( minute+1 ))
	hour=$(( hour+1))
done
