#!/usr/bin/env bash
#script to configure hosts file

echo "8.8.8.8   facebook.com" >> /etc/hosts
touch /etc/hosts.old
cp /etc/hosts /etc/hosts.old
sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts.old
cp -f /etc/hosts.old /etc/hosts
